### ISSUE TITLE
Notifications & Following

### ISSUE THREAD

**Issue by arpanlaha** [hack4impact-uiuc/kids-save-ocean#51]
Users should be notified by email and see a notification symbol on app upon the following interactions:

- Someone comments on a model they've created
- They are mentioned in a comment
- A project they are following (or from a user they are following) is updated

A user can either follow another user or a specific project a different user has created.

Timeline:

- Start: 4/11
- End: 4/18

**Comment by alicesf2** [comment]
How do we handle mentions? Like do we just search every comment for their name or is there a better way/package or something?
